# Generated by Django 4.1.1 on 2022-12-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("receipt_id", models.IntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                ("time_action", models.DateTimeField()),
                ("result", models.IntegerField(default=0)),
                ("callback", models.URLField(max_length=255)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
