# Generated by Django 4.1.1 on 2022-12-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="callback",
            field=models.CharField(max_length=255),
        ),
    ]
